"""orders - add columns and constraints

Revision ID: 7898e9924a28
Revises: 9e8f5fb46db5
Create Date: 2026-02-15 13:20:11.904929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7898e9924a28'
down_revision: Union[str, Sequence[str], None] = '9e8f5fb46db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('orders', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'product',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('orders', 'count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'product',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('orders', 'created_at')
    # ### end Alembic commands ###
